#!/usr/bin/env bash
# build.sh — compile Aloud in release and assemble a runnable .app bundle under
# dist/, ad-hoc signed. Menubar only, no Dock icon (LSUIElement in the Info.plist).
# Run from anywhere; paths resolve relative to the kokoro/ project root.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
cd "$root"

app_name="Aloud"
exec_name="AloudBar"
bundle="dist/${app_name}.app"

echo "==> swift build -c release"
swift build -c release --product "$exec_name"
swift build -c release --product aloud-apple

bin_path="$(swift build -c release --product "$exec_name" --show-bin-path)/${exec_name}"
if [ ! -x "$bin_path" ]; then
  echo "error: built executable not found at $bin_path" >&2
  exit 1
fi

echo "==> assembling ${bundle}"
rm -rf "$bundle"
mkdir -p "${bundle}/Contents/MacOS" "${bundle}/Contents/Resources"

cp "$bin_path" "${bundle}/Contents/MacOS/${exec_name}"
# The Apple engine's helper rides along in the bundle; install.sh copies it into
# ~/.aloud, where the daemon looks first.
cp "$(dirname "$bin_path")/aloud-apple" "${bundle}/Contents/MacOS/aloud-apple"
cp "$here/Info.plist" "${bundle}/Contents/Info.plist"
# Ensure the executable name in the plist matches the copied binary.
/usr/libexec/PlistBuddy -c "Set :CFBundleExecutable ${exec_name}" "${bundle}/Contents/Info.plist" >/dev/null

# App icon (generated by _dev/icon/make_icon.swift; Info.plist points
# CFBundleIconFile at AppIcon). Shows in Finder, Launchpad and /Applications even
# though the app is LSUIElement and never appears in the Dock.
if [ -f "$here/icon/AppIcon.icns" ]; then
  echo "==> app icon"
  cp "$here/icon/AppIcon.icns" "${bundle}/Contents/Resources/AppIcon.icns"
else
  echo "    warning: _dev/icon/AppIcon.icns missing — run: swift _dev/icon/make_icon.swift" >&2
fi

echo "==> ad-hoc codesign"
codesign --force --deep -s - "$bundle"
codesign -dv "$bundle" 2>&1 | sed 's/^/    /' || true

echo "==> done: ${root}/${bundle}"
